# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "44baf452c3f2b1fc7a9ebb796e21b9c6"
name = "kev-test"
handle = "kev-test"
application_url = "https://awarded-markets-mutual-hello.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://awarded-markets-mutual-hello.trycloudflare.com/auth/callback",
  "https://awarded-markets-mutual-hello.trycloudflare.com/auth/shopify/callback",
  "https://awarded-markets-mutual-hello.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
